config/routes.rb
Rails.application.routes.draw do

  root :to => 'moods#index'

  get "/songs/get_song" => 'songs#get_song'

  get "/moods/get_moods" => 'moods#get_moods'

  get "/moods/save_mood" => 'moods#save_mood'

  get "/songs/get_all_songs" => 'songs#get_all_songs'

  resources :moods, :only =>[:index, :show] do
    resources :songs, :only =>[:index, :show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mood.rb
class Mood < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :mood

end

app/models/spotify.rb
class Spotify

  attr_accessor :uri, :artist, :track

  # need to add artist and track params
  def initialize(artist, track)
    @artist = artist
    @track = track

    url =("https://api.spotify.com/v1/search?q=" + track + "&type=track")

    response = HTTParty.get(url).parsed_response

    @uri = response['tracks']['items'][0]['uri']


    # ['artists']['items'][0]['uri']
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController

  def index
    @moods = Mood.all
  end

  def get_moods
    @moods = Mood.all
    respond_to do |format|
      format.json { render json: @moods }
      format.html { render :show}
    end
  end

  def save_mood

    @song = Song.create!(uri: "#{params[:uri]}", mood_id: params[:id])    
  end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
  end

  def get_song
    @response = Spotify.new(params[:artist], params[:track])
    respond_to do |format|
      format.json { render json: @response }
      format.html { render :show}
    end
  end

  def get_all_songs
    @songs = Song.where(mood_id: params[:id])
    respond_to do |format|
      format.json { render json: @songs }
      format.html { render :show}
    end
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mood_helper.rb
module MoodHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoodPlayer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moods/index.html.erb
<h1>Mood#index</h1>
<p>Find me in app/views/mood/index.html.erb</p>
<div class="get">
  GET OBJECT
</div>
<% @moods.each do |mood| %>

  <div>
    <h2><%= link_to mood.name, mood_songs_path(mood.id) %></h2>
  </div>
<% end %>


<br />

<label>Artist:</label>
 <input class="artist" type="text">
 <label>Track:</label>
 <input class="track" type="text">

<br />
<br />
<br />
<br />
<iframe src="https://embed.spotify.com/?uri=spotify:track:7oK9VyNzrYvRFo7nQEYkWN" frameborder="0" allowtransparency="true"></iframe><br />
<iframe src="https://embed.spotify.com/?uri=spotify:track:5JunxkcjfCYcY7xJ29tLai" frameborder="0" allowtransparency="true"></iframe><br />
<iframe src="https://embed.spotify.com/?uri=spotify:user:erebore:playlist:788MOXyTfcUb1tdw4oC7KJ&view=coverart" frameborder="0" allowtransparency="true"></iframe><br />
<iframe src="https://embed.spotify.com/?uri=spotify:user:erebore:playlist:788MOXyTfcUb1tdw4oC7KJ&theme=white" frameborder="0" allowtransparency="true"></iframe><br />
<iframe src="https://embed.spotify.com/?uri=spotify:user:erebore:playlist:788MOXyTfcUb1tdw4oC7KJ&theme=white&view=coverart" frameborder="0" allowtransparency="true"></iframe><br />
<iframe src="https://embed.spotify.com/?uri=spotify:track:0g5EKLgdKvNlln7TNqBByK" width="300" height="380" frameborder="0" allowtransparency="true"></iframe><br />

<p>
  Song.create!(title: "Mr. Brightside", artist: "The Killers", album: "Hot Fuss", album_url: "https://i.scdn.co/image/ac68a9e4a867ec3ce8249cd90a2d7c73755fb487", uri: "spotify:track:7oK9VyNzrYvRFo7nQEYkWN", song_length: 222200, votes: 0, mood_id: 1)
</p>




<h1><%= link_to "back to home", root_path%></h1>

app/views/moods/show.html.erb
<h1>Mood#show</h1>
<p>Find me in app/views/mood/show.html.erb</p>

<h1>This is the response</h1>

<%= @uri.uri %>

app/views/songs/delete.html.erb
<h1>Song#delete</h1>
<p>Find me in app/views/song/delete.html.erb</p>

app/views/songs/index.html.erb
<h1>Song#index</h1>
<p>Find me in app/views/song/index.html.erb</p>


<% @songs.each do |song| %>
  <div>
    <%= song.title %>
  </div>
<% end %>


<h1><%= link_to "back to home", root_path%></h1>

app/views/songs/show.html.erb
<h1>Song#show</h1>
<p>Find me in app/views/song/show.html.erb</p>